ignorePaths:
  - .env
  - .git
  - .github
  - .nuxt
  - .output
  - amplify/**/*.json
  - cspell.config.yaml
  - dist
  - node_modules
  - src/aws-exports.js
  - src/public
words:
  - nuxi
  - nuxt
  - nuxtjs
  - pinia
  - stylelint
  - vuetify
